force ci to fail to check cd logic

diff --git a/.github/workflows/cd_dev.yml b/.github/workflows/cd_dev.yml
--- a/.github/workflows/cd_dev.yml
+++ b/.github/workflows/cd_dev.yml
@@ -108,11 +108,10 @@ jobs:
     - name: Continuous Integration Failed
       if: steps.wait-for-build.outputs.conclusion != 'success'
       run: |
-        echo "Error! $The continuous Integration workflow has status of [${{steps.wait-for-build.outputs.conclusion}}]" 1>&2
+        echo "Error! The continuous Integration workflow has status of [${{steps.wait-for-build.outputs.conclusion}}]" 1>&2
         exit 64
 
     - name: Download artifact package
-      if: steps.wait-for-build.outputs.conclusion == 'success'
       uses: dawidd6/action-download-artifact@v2
       with:
         github_token: ${{secrets.GITHUB_TOKEN}}
@@ -122,18 +121,15 @@ jobs:
         path: ./build/dist
 
     - name: Display structure of downloaded files
-      if: steps.wait-for-build.outputs.conclusion == 'success'
       run: ls -R
       working-directory: ./build/dist
 
     - name: Login to Get KeyVault Secrets
-      if: steps.wait-for-build.outputs.conclusion == 'success'
       uses: Azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
 
     - name: Get KeyVault Secrets
-      if: steps.wait-for-build.outputs.conclusion == 'success'
       uses: Azure/get-keyvault-secrets@v1.0
       with:
         keyvault: "simulationchicken"
@@ -141,7 +137,6 @@ jobs:
       id: get_secret_action
       
     - name: Get Deploy Secrets
-      if: steps.wait-for-build.outputs.conclusion == 'success'
       run: |
         echo 'DEPLOY_CREDENTIAL<<EOF' >> $GITHUB_ENV
         echo '{' >> $GITHUB_ENV
@@ -153,13 +148,11 @@ jobs:
         echo 'EOF' >> $GITHUB_ENV
 
     - name: Login via Azure CLI
-      if: steps.wait-for-build.outputs.conclusion == 'success'
       uses: azure/login@v1
       with:
         creds: ${{ env.DEPLOY_CREDENTIAL }}
 
     - name: Azure Functions Action
-      if: steps.wait-for-build.outputs.conclusion == 'success'
       uses: Azure/functions-action@v1.1.5
       with:
         app-name: mykvapp1027
@@ -178,8 +171,24 @@ jobs:
     steps:
     - name: Checkout
       uses: actions/checkout@v2
+
+    - name: Wait for Continuous Integration to Succeed
+      uses: fountainhead/action-wait-for-check@v1.0.0
+      id: wait-for-build
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+        checkName: 'Generate Build Reference'
+        ref: ${{ github.event.pull_request.head.sha || github.sha }}
+        timeoutSeconds: 600
+        intervalSeconds: 10
+
+    - name: Continuous Integration Failed
+      if: steps.wait-for-build.outputs.conclusion != 'success'
+      run: |
+        echo "Error! The continuous Integration workflow has status of [${{steps.wait-for-build.outputs.conclusion}}]" 1>&2
+        exit 64
+
     - name: Download artifact package
-      if: steps.wait-for-build.outputs.conclusion == 'success'
       uses: dawidd6/action-download-artifact@v2
       with:
         github_token: ${{secrets.GITHUB_TOKEN}}
@@ -187,6 +196,7 @@ jobs:
         branch: master
         name: ref-build-package
         path: ./build
+
     - name: Checkout Branch
       run: |
         git checkout stage_config
