cd

diff --git a/.github/workflows/cd_stage.yml b/.github/workflows/cd_stage.yml
--- a/.github/workflows/cd_stage.yml
+++ b/.github/workflows/cd_stage.yml
@@ -23,7 +23,7 @@ jobs:
     # wait on continuous deployment for dev
     - name: Wait for Dev to Succeed
       uses: fountainhead/action-wait-for-check@v1.0.0
-      id: wait-for-dev
+      id: wait-for-dev-infra
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         checkName: 'Deploy Dev Infra'
@@ -34,13 +34,19 @@ jobs:
     # wait on continuous deployment for dev
     - name: Wait for Dev to Succeed
       uses: fountainhead/action-wait-for-check@v1.0.0
-      id: wait-for-dev
+      id: wait-for-dev-app
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         checkName: 'Deploy Dev App'
         ref: a4211c9c23b37f524fee6dd38bccb9d58bd1af37
         timeoutSeconds: 30
         intervalSeconds: 10
+
+    - name: Dev Check Failed
+      if: steps.wait-for-dev-infra.outputs.conclusion != 'success'  || steps.wait-for-dev-app.outputs.conclusion != 'success' 
+      run: |
+        echo "Error! The Dev Continuous Deployment workflow has status of [${{steps.wait-for-build.outputs.conclusion}}]" 1>&2
+        exit 64
 
   terraform:
     needs: checks
